import { adminNavigation, adminNavigationStyles } from './admin-navigation.js'

export const apiKeyDashboardHtml = String.raw`<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>API 密钥 · EVA</title><style>
  *{box-sizing:border-box}body{margin:0;color:#dceae5;background:#07110f;font-family:"Noto Sans SC",system-ui,sans-serif}${adminNavigationStyles}
  main{width:min(1000px,calc(100% - 40px));margin:48px auto}.eyebrow{color:#59d6ad;font:600 11px monospace;letter-spacing:.12em}h1{margin:8px 0;font-size:32px}.lead{color:#82968f;margin:0 0 30px}
  .panel{padding:24px;border:1px solid #1d342d;border-radius:14px;background:#0b1916;margin-bottom:20px}.create{display:flex;gap:12px}input{flex:1;padding:12px 14px;border:1px solid #29473d;border-radius:9px;color:#eef8f4;background:#081310;font:inherit}button{padding:11px 16px;border:0;border-radius:9px;color:#061410;background:#59d6ad;font-weight:700;cursor:pointer}.secondary{padding:7px 10px;color:#a8c5bb;background:#142923}.danger{padding:7px 10px;color:#ff968b;background:#2b1716}.actions{display:flex;gap:7px;justify-content:flex-end;white-space:nowrap}
  table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:14px 10px;border-bottom:1px solid #193029}th{color:#70877f;font-size:12px}code{color:#8ee7ca}.secret-value{display:inline-block;max-width:330px;overflow:hidden;text-overflow:ellipsis;vertical-align:middle}.empty{padding:24px 10px;color:#70877f}.notice{display:none;padding:18px;margin-top:18px;border:1px solid #4d806e;border-radius:10px;background:#102c24}.notice code{display:block;margin:10px 0;padding:12px;overflow-wrap:anywhere;background:#07110f}.hint{color:#82968f;font-size:13px}
  @media(max-width:700px){main{width:calc(100% - 24px)}.create{flex-direction:column}.created{display:none}}
</style></head><body>${adminNavigation('keys')}<main>
  <div class="eyebrow">ACCESS CONTROL / API KEYS</div><h1>API 密钥</h1><p class="lead">为 CLI 创建独立凭据。可随时显示或复制密钥，服务端使用加密文件保存。</p>
  <section class="panel"><form class="create" id="create-form"><input id="key-name" maxlength="80" required placeholder="密钥名称，例如：research-mac"><button type="submit">创建密钥</button></form><div class="notice" id="notice"><strong>密钥已创建</strong><code id="created-key"></code><button class="secondary" id="copy-created" type="button">复制密钥</button></div></section>
  <section class="panel"><table><thead><tr><th>名称</th><th>密钥</th><th class="created">创建时间</th><th></th></tr></thead><tbody id="key-list"></tbody></table><div class="empty" id="empty">暂无 API 密钥</div></section>
</main><script>
const list=document.getElementById('key-list'),empty=document.getElementById('empty');
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(){const r=await fetch('/v1/api-keys');const body=await r.json();list.innerHTML=(body.data||[]).map(k=>'<tr><td>'+esc(k.name)+'</td><td><code class="secret-value" data-secret="'+esc(k.id)+'">'+esc(k.recoverable?'••••••••••••••••••••':k.prefix+'…（需重建后查看）')+'</code></td><td class="created">'+esc(new Date(k.created_at).toLocaleString())+'</td><td><div class="actions">'+(k.recoverable?'<button class="secondary" data-action="toggle" data-id="'+esc(k.id)+'">显示</button><button class="secondary" data-action="copy" data-id="'+esc(k.id)+'">复制</button>':'')+'<button class="danger" data-action="revoke" data-id="'+esc(k.id)+'">撤销</button></div></td></tr>').join('');empty.style.display=list.children.length?'none':'block'}
async function secret(id){const r=await fetch('/v1/api-keys/'+encodeURIComponent(id)+'/secret');const body=await r.json();if(!r.ok)throw new Error(body.detail||'读取密钥失败');return body.data.key}
async function copy(value){if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(value)}else{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();document.execCommand('copy');area.remove()}}
document.getElementById('create-form').addEventListener('submit',async e=>{e.preventDefault();const r=await fetch('/v1/api-keys',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:document.getElementById('key-name').value})});const body=await r.json();if(!r.ok){alert(body.detail||'创建失败');return}document.getElementById('created-key').textContent=body.data.key;document.getElementById('notice').style.display='block';e.target.reset();await load()});
document.getElementById('copy-created').addEventListener('click',async e=>{await copy(document.getElementById('created-key').textContent);e.target.textContent='已复制';setTimeout(()=>e.target.textContent='复制密钥',1500)});
list.addEventListener('click',async e=>{const action=e.target.dataset?.action,id=e.target.dataset?.id;if(!action||!id)return;try{if(action==='revoke'){if(!confirm('确认撤销此密钥？使用它的 CLI 将立即无法访问。'))return;await fetch('/v1/api-keys/'+encodeURIComponent(id),{method:'DELETE'});await load();return}const value=await secret(id);if(action==='copy'){await copy(value);e.target.textContent='已复制';setTimeout(()=>e.target.textContent='复制',1500);return}const field=list.querySelector('[data-secret="'+CSS.escape(id)+'"]');const showing=field.dataset.showing==='true';field.textContent=showing?'••••••••••••••••••••':value;field.dataset.showing=String(!showing);e.target.textContent=showing?'显示':'隐藏'}catch(error){alert(error.message)}});load();
</script></body></html>`
